export const GET_EVENTS_FROM_DAY = "GET_EVENTS_FROM_DAY"
export const REMOVE_EVENT = "REMOVE_EVENT"
export const REMOVE_EVENT_SUCCESS = "REMOVE_EVENT_SUCCESS"
export const REMOVE_EVENT_ERROR = "REMOVE_EVENT_ERROR"